# Generated by Django 4.2.6 on 2023-10-22 14:43

from django.db import migrations, models
import myprofile.models

class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=myprofile.models.avatar_directory_path),
        ),
    ]
