# Generated by Django 4.2.6 on 2023-10-23 21:12

from django.db import migrations, models
import myprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0008_alter_profile_email_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=myprofile.models.avatar_directory_path),
        ),
    ]
