# Generated by Django 4.2.6 on 2023-10-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_product_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['pk'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
