# Generated by Django 4.2.6 on 2023-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_remove_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('free_shipping_on_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
            ],
        ),
    ]
