# Generated by Django 4.2.6 on 2023-11-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0031_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
