# Generated by Django 4.2.6 on 2023-11-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0033_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='days_of_life',
        ),
        migrations.AddField(
            model_name='basket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('deliveryType', models.CharField(default='ordinary', max_length=10)),
                ('paymentType', models.CharField(default='online', max_length=10)),
                ('totalCost', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_auth_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopapp.order'),
        ),
    ]
