# Generated by Django 4.2.6 on 2023-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0034_remove_basket_days_of_life_basket_archived_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
