# Generated by Django 4.2.6 on 2023-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0038_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
