# Generated by Django 4.2.6 on 2023-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0039_product_saleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
